### ISSUE TITLE
Про обновление до версии 1.3

### ISSUE THREAD

**Issue by BlankShade98** [the-dise/Mir-Pay-Wallet#2]
После обновления до версии 1.3 приложение может вылетать при запуске. Сброс данных приложения решает проблему.

**Comment by the-dise** [comment]
Обновление с какой версии было?

**Comment by BlankShade98** [comment]
1.2, в настройках были выбраны параметры 60 сек и карта TINKOFF (в 1.3 переименована в TINKOFF_BLACK, возможно причина вылета была в этом)

**Comment by the-dise** [comment]
Да, проверил и проблема дествительно из-за карты. Постараюсь исправить
