### ISSUE TITLE
[Question] Should I install the usual mirpay app on watch?

### ISSUE THREAD

**Issue by SpiritOTHawk** [the-dise/Mir-Pay-Wallet#7]
Or only on phone?

**Comment by the-dise** [comment]
You need to install the Mir Pay app on your watch. The most stable version of the app is **_1.18.3.347_**, but recently it stopped working, yesterday I updated to **_1.41.3.3.342_** and it works, but I haven't tested it in stores yet. 

**Installation instructions:**
- Install Mir Pay APK by any convenient method on your watch.
- Set the watch's screen density to 150 for easy customization
```adb shell
   wm density 150 
```
- Add your card to the app using the prompts in the app itself.
- Go to Settings → Connections → NFC → Tap & Pay and select Mir Pay as your primary contactless payment option.
- Return the screen density to the default value
```adb shell
   wm density reset
```

**Comment by SpiritOTHawk** [comment]
Thanks

**Comment by the-dise** [comment]
I tested version **_Mir Pay 1.41.3.3.342_** on my Pixel Watch First Gen (WearOS 4.0 Build: TWD9.240405.001) and everything works great
